.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. badinvestmentcoin_qt test_badinvestmentcoin_qt
clean: FORCE
	$(MAKE) -C .. badinvestmentcoin_qt_clean test_badinvestmentcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_badinvestmentcoin_qt_check
badinvestmentcoin-qt badinvestmentcoin-qt.exe: FORCE
	 $(MAKE) -C .. badinvestmentcoin_qt
